#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true
package_repository: ppa:ansible/ansible
packages:
  - software-properties-common
  - git
  - ansible
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCfOooDqFPAeeYYdXzY6BNSFga5QjdXAorwTWXmaTUv49qQWGcEioIlXTFo0bPSekd7ZHUyi6qJ7RaODNZkligwCkhg9+4jwAF8pvsTRH77MU9NC9Im3nz9hqzSvvfpGHpXoVmWoWt1SdI5+T3dHf05dsGm30/rJYa0E1/mZw+cKlsxkQXbxUhanoqnstADvd26yBYkN7lQpyRBTDwcOGX939M1E5qo1J2gSbtWQJVoZ3dNQk5pf88tCH5lZVIHbBQLgDY/MknSRp8hbZALvA4WMOSBCC7+fAVhYpwKb0ALmtX3eERi16gCSUAZrJmgIafmSvSDdhUa2eOUy5he2SB1
runcmd:
  - mkdir /mnt/block_storage
  - ansible-galaxy collection install kubernetes.core
#  - cat /dev/urandom | tr -dc 'a-zA-Z0-9_+-' | head -c 32 > /run/galaxy_api_key
  - echo galaxypassword > /run/galaxy_api_key
  - cat /dev/urandom | tr -dc 'a-zA-Z0-9_+-' | head -c 32 > /run/pulsar_api_key
#  - git clone https://github.com/galaxyproject/galaxy-k8s-boot.git /run/galaxy-k8s-boot
  - git clone --single-branch --branch gcp https://github.com/ksuderman/galaxy-k8s-boot.git /run/galaxy-k8s-boot
  - ip=$(curl -s ifconfig.me) && cd /run/galaxy-k8s-boot && cat inventories/localhost.template | sed "s/__HOST__/$ip/g" | sed "s/__USER__/ubuntu/" | sed "s/localhost/$ip/g" > inventories/localhost
  - cd /run/galaxy-k8s-boot && ansible-playbook -i inventories/localhost playbook.yml --extra-vars "job_max_cores=$(($(nproc) - 2))" --extra-vars "job_max_mem=$(($(free -m | awk '/^Mem:/{print $2}') - 6144))" --extra-vars "application=galaxy" --extra-vars "galaxy_api_key=$(cat /run/galaxy_api_key)" --extra-vars "pulsar_api_key=$(cat /run/pulsar_api_key)" -e "galaxy_admin_users=admin@example.com"




