ingress:
  enabled: true
  ingressClassName: ""
  canary:
    enabled: false
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
  - host: ~
    paths:
    - path: /
  path: /

image:
  repository: ksuderman/galaxy-min
  tag: "25.1-batch"
#  repository: quay.io/galaxyproject/galaxy-min
#  tag: "24.2.1-uid"

#setupJob:
#  securityContext:
#    runAsUser: 0
jobs:
  rules:
    tpv_rules_local.yml:
      tools:
        toolshed.g2.bx.psu.edu/repos/iuc/metaphlan/metaphlan/.*:
          cores: 16
          mem: 96

resources:
  limits:
    memory: 64G

persistence:
  storageClass: nfs
  size: 20Gi

cvmfs:
  deployPostInstallFix: true
  cvmfscsi:
    cache:
      local:
        enabled: true
        pvc:
          storageClass: nfs
          name: cvmfs-local-cache
      alien:
        enabled: false
        pvc:
          name: cvmfs-alien-cache
    logVerbosityLevel: 5

postgresql:
  persistence:
    storageClass: blockstorage

rabbitmq:
  persistence:
    storageClassName: blockstorage

configs:
  job_conf.yml:
    runners:
      k8s:
        k8s_fs_group_id: '10001'
        k8s_run_as_group_id: '10001'
        k8s_run_as_user_id: '10001'
        k8s_supplemental_group_id: '10001'
  galaxy.yml:
    galaxy:
      require_login: true
      show_welcome_with_login: true
      allow_user_creation: false
      job_metrics:
        - type: core
        - type: cgroup
        - type: cpuinfo
        - type: meminfo
        - type: uname
extraFileMappings:
  /galaxy/server/static/welcome.html:
    applyToWeb: true
    applyToNginx: true
    content: |
      <!DOCTYPE html>
      <html lang="en">
          <head>
              <meta charset="utf-8" />
              <link rel="stylesheet" href="dist/base.css" type="text/css" />
          </head>
          <body class="m-0">
              <div class="py-4">
                  <div class="container">
                      <div class="row mb-4">
                          <div class="col-md-12">
                              <h2>Welcome to Galaxy on ACCP</h2>
                              <p>
                                  Galaxy is an interactive and workflow analysis
                                  platform providing a graphical user interface
                                  for computational tools. This is your own
                                  Galaxy instance running on the ACCP platform
                                  that you can customize and use for your own
                                  research. You can also add others users to
                                  this Galaxy instance via the ACCP portal.
                              </p>
                          </div>
                      </div>
                  </div>
              </div>
          </body>
      </html>
