---
# Optimized runtime playbook for single-node RKE2 deployments on pre-prepared Ubuntu 24.04+ images.
# This playbook assumes RKE2, Helm, and Helm repositories are pre-cached via image_prep.yml role.
# IMPORTANT: This playbook only works with Ubuntu 24.04+ images prepared by the image_preparation role.
#
# Features:
# - Single-node RKE2 cluster (master node runs workloads)
# - Pre-installed RKE2 binaries for faster deployment
# - Automatic taint removal for workload scheduling on master
# - Optimized for Galaxy deployment scenarios
# - Minimal fact gathering for maximum speed

- name: Fast runtime configuration and RKE2 cluster setup (single play for speed)
  hosts: k8s_cluster
  gather_facts: true  # Only gather facts once at the very beginning
  tasks:
    # Initial system preparation tasks
    - name: Regenerate SSH host keys
      shell: |
        ssh-keygen -A
        systemctl restart ssh
      become: true

    - name: Start required services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: true
        daemon_reload: true
      loop:
        - containerd
        - autofs
      become: true

    - name: Initialize machine-id
      shell: systemd-machine-id-setup
      become: true

    - name: Ensure ubuntu user kubeconfig directory
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
      become: true

    # RKE2 setup tasks (single-node = master and worker)
    - name: Create RKE2 server configuration for single-node cluster
      copy:
        dest: /etc/rancher/rke2/config.yaml
        mode: '0600'
        content: |
          write-kubeconfig-mode: "0644"
          # Single-node cluster configuration
          cluster-init: true
          token: "{{ rke2_token }}"
          tls-san:
            - "{{ ansible_default_ipv4.address }}"
            - "{{ ansible_ssh_host | default(ansible_host) }}"
            - 127.0.0.1
            - localhost
          {% for san in rke2_additional_sans | default([]) %}
            - "{{ san }}"
          {% endfor %}
          bind-address: "{{ rke2_bind_address | default('0.0.0.0') }}"
          disable:
          {% for component in rke2_disable | default(['rke2-traefik', 'rke2-ingress-nginx']) %}
            - "{{ component }}"
          {% endfor %}
          cni:
            - canal
          {% if rke2_debug | default(false) %}
          debug: true
          {% endif %}
          # Allow workloads to be scheduled on master node (single-node setup)
          # No taints applied to allow pods to run on the master
      become: true

    - name: Start and enable RKE2 server
      systemd:
        name: rke2-server
        state: started
        enabled: true
        daemon_reload: true
      become: true

    - name: Wait for RKE2 server to be ready
      wait_for:
        port: 6443
        host: "{{ ansible_default_ipv4.address }}"
        delay: 10
        timeout: 300

    # Post-cluster configuration tasks
    - name: Remove master node taint to allow workload scheduling
      shell: |
        /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml taint nodes --all node-role.kubernetes.io/control-plane- || true
        /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml taint nodes --all node-role.kubernetes.io/master- || true
      become: true

    - name: Copy kubeconfig to ubuntu user
      copy:
        src: /etc/rancher/rke2/rke2.yaml
        dest: /home/ubuntu/.kube/config
        owner: ubuntu
        group: ubuntu
        mode: '0600'
        remote_src: true
      become: true

    - name: Update kubeconfig server address for ubuntu user
      replace:
        path: /home/ubuntu/.kube/config
        regexp: 'https://127\.0\.0\.1:6443'
        replace: "https://{{ ansible_default_ipv4.address }}:6443"
      become: true

    - name: Add RKE2 bin directory to ubuntu user's PATH
      lineinfile:
        path: /home/ubuntu/.bashrc
        line: 'export PATH=/var/lib/rancher/rke2/bin:$PATH'
        create: true
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      become: true

    - name: Add KUBECONFIG to ubuntu user's environment
      lineinfile:
        path: /home/ubuntu/.bashrc
        line: 'export KUBECONFIG=/home/ubuntu/.kube/config'
        create: true
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      become: true

# Import playbooks with fact gathering disabled (use cached facts from above)
- name: Install NFS
  import_playbook: nfs.yml

- name: Configure storage
  import_playbook: storage.yml

- name: Configure Ingress
  import_playbook: ingress.yml

- name: Install Galaxy
  import_playbook: galaxy_app.yml
  vars:
    values_file: "values/{{ chart_values_file | default('accp.yml') }}"
    gxy_admin_users: "{{ galaxy_admin_users | default('') }}"
    gxy_api_key: "{{ galaxy_api_key }}"
  when: application == "galaxy"
