FROM ubuntu:24.04

ARG APP_DIR=/opt/galaxy-k8s-boot
ARG KUBE_CLOUD_PROVIDER=openstack
ARG K8S_PROVIDER=rke

# Prevent interaction from apt
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    dbus \
    systemd \
    systemd-sysv \
    iproute2 \
    curl \
    python3 \
    python3-pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Remove unnecessary systemd services
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
    rm -f /lib/systemd/system/multi-user.target.wants/*; \
    rm -f /lib/systemd/system/local-fs.target.wants/*; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /lib/systemd/system/basic.target.wants/*; \
    rm -f /lib/systemd/system/anaconda.target.wants/*

ADD . $APP_DIR
WORKDIR $APP_DIR

RUN pip install --upgrade pip && pip install -r requirements.txt

# Ensure D-Bus machine ID is generated
RUN dbus-uuidgen --ensure

# Set up entrypoint to use systemd
#ENTRYPOINT ["/lib/systemd/systemd"]
CMD ["ansible-playbook", "-i", "inventories/hosts.ini", "playbook.yml", "-e", "kube_cloud_provider=$KUBE_CLOUD_PROVIDER", "-e", "k8s_provider=$K8S_PROVIDER", "-e", "-break-system-packages", "--connection=local"]
