apiVersion: v1
kind: PersistentVolume
metadata:
  name: galaxy-pv
  labels:
    app: galaxy
spec:
  capacity:
    storage: 100Gi  # Adjust size as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - vers=4.1
    - hard
    - intr
    - rsize=1048576
    - wsize=1048576
    - timeo=600
    - retrans=2
    - locks
    - local_lock=all
    - fsc
  nfs:
    server: NFS_SERVER_IP  # Replace with actual LoadBalancer IP
    path: /