---
- name: Setup the Galaxy application
  hosts: controllers[0]
  vars:
    chart: cloudve/galaxy
    version: 5.17.0
    image: quay.io/galaxyproject/galaxy-min
    tag: 24.1
    galaxy_admin_users: "suderman@jhu.edu"
    galaxy_api_key: galaxypassword
    job_max_cores: 1
    job_max_mem: 4
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"
  tasks:
    - name: Create the galaxy namespace
      kubernetes.core.k8s:
        kind: Namespace
        name: galaxy
        state: present

    - name: Copy the values file to the remote host
      ansible.builtin.copy:
        src: "{{ values_file }}"
        dest: /tmp/values.yml
        mode: '0644'

    - name: Helm install Galaxy
      kubernetes.core.helm:
        name: galaxy
        namespace: galaxy
        chart_ref: "{{ chart }}"
        chart_version: "{{ version }}"
        values_files:
          - /tmp/values.yml
        values:
          configs:
            galaxy.yml:
              galaxy:
                admin_users: "{{ galaxy_admin_users }}"
                master_api_key: "{{ galaxy_api_key }}"
          image:
            repository: "{{ image }}"
            tag: "{{ tag }}"
          jobs:
            rules:
              tpv_rules_local.yml:
                destinations:
                  k8s:
                    max_cores: "{{ job_max_cores }}"
                    max_mem: "{{ job_max_mem }}"
#        postgresql:
#          galaxyDatabasePassword: galaxydbpassword
