---
- name: Setup Helm
  hosts: controllers[0]
  vars:
    repositories:
      - name: stable
        url: https://charts.helm.sh/stable
      - name: cloudve
        url: https://raw.githubusercontent.com/CloudVE/helm-charts/master/
      - name: ksuderman
        url: https://ksuderman.github.io/helm_charts
  tasks:
    - name: Install Helm
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: "set -o pipefail && curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash -s"
        creates: /usr/local/bin/helm
      become: true

    - name: Remove existing stable Helm repo
      kubernetes.core.helm_repository:
        name: stable
        state: absent

    - name: Install Helm repositoryies
      kubernetes.core.helm_repository:
        name: "{{ item.name }}"
        state: present
        repo_url: "{{ item.url }}"
      loop:
        - name: stable
          url: https://charts.helm.sh/stable
        - name: cloudve
          url: https://raw.githubusercontent.com/CloudVE/helm-charts/master/
        - name: ksuderman
          url: https://ksuderman.github.io/helm_charts
