---
# Optimized image preparation playbook - minimal fact gathering for speed
- name: Prepare machine image with pre-installed components for RKE2
  hosts: all
  become: true
  gather_facts: true  # Only gather facts once at the start
  vars:
    # Cache facts to avoid re-gathering
    ansible_facts_gathering: smart
    ansible_facts_cache: true
    # Override these variables as needed
    rke2_version: v1.33.4+rke2r1  # https://github.com/rancher/rke2/tags
    helm_version: v3.17.4  # https://github.com/helm/helm/tags

    # Package installation flags
    install_base_packages: true
    install_cvmfs: true
    install_rke2_prerequisites: true
    install_helm: true

    # CVMFS configuration (galaxyproject.cvmfs role)
    cvmfs_role: client
    galaxy_cvmfs_repos_enabled: config-repo
    cvmfs_quota_limit: 4000
    cvmfs_http_proxies: ["DIRECT"]
    # Repos to test explicitly
    cvmfs_verify_repos:
      - data.galaxyproject.org

  pre_tasks:
    - name: Display target host information
      ansible.builtin.debug:
        msg: |
          Preparing image for host: {{ inventory_hostname }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Architecture: {{ ansible_architecture }}

    - name: Update system packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        autoremove: true
        autoclean: true

    - name: Install base packages early (needed for CVMFS role keys)
      ansible.builtin.import_tasks: roles/image_preparation/tasks/base_packages.yml
      when: install_base_packages | bool

  roles:
    # Roles will use facts gathered at playbook start (no re-gathering)
    - role: galaxyproject.cvmfs
      when: install_cvmfs | bool

    - role: image_preparation

  post_tasks:
    # Fast verification checks (no fact re-gathering needed)
    - name: Verify CVMFS client installed
      ansible.builtin.command: which cvmfs_config
      register: cvmfs_config_check
      changed_when: false
      failed_when: install_cvmfs and cvmfs_config_check.rc != 0
      when: install_cvmfs | bool

    - name: Probe CVMFS configuration
      ansible.builtin.command: cvmfs_config probe
      register: cvmfs_probe
      changed_when: false
      failed_when: false
      when: install_cvmfs | bool

    - name: Show CVMFS probe output
      ansible.builtin.debug:
        var: cvmfs_probe.stdout
      when: install_cvmfs | bool and cvmfs_probe is defined

    - name: Ensure autofs service running for CVMFS
      ansible.builtin.service:
        name: autofs
        state: started
        enabled: true
      when: install_cvmfs | bool
      failed_when: false

    - name: Wait for CVMFS base directory
      ansible.builtin.stat:
        path: /cvmfs
      register: cvmfs_basedir
      retries: 5
      delay: 2
      until: not install_cvmfs or cvmfs_basedir.stat.exists

    - name: Attempt mount of CVMFS repositories
      when: install_cvmfs | bool
      block:
        - name: Trigger on-demand mount by listing repo root
          ansible.builtin.command: ls -1 /cvmfs/{{ item }}/
          register: cvmfs_repo_list
          changed_when: false
          failed_when: false
          loop: "{{ cvmfs_verify_repos }}"
          loop_control:
            label: "{{ item }}"

        - name: Summarize CVMFS repo mount results
          ansible.builtin.debug:
            msg: |
              CVMFS mount results:
              {% for r in cvmfs_repo_list.results %}
              - {{ r.item }}: {{ 'OK' if r.rc == 0 else 'FAILED rc=' + (r.rc|string) }}
              {% endfor %}

    - name: Fail if any required CVMFS repo failed to mount
      when: install_cvmfs and (cvmfs_repo_list is defined) and (cvmfs_repo_list.results | selectattr('rc','ne',0) | list | length > 0)
      ansible.builtin.fail:
        msg: "CVMFS repository mount failures detected. See previous task output."

    - name: Display installed components summary
      ansible.builtin.debug:
        msg: |
          === Image Preparation Complete ===
          Base packages: {{ 'Installed' if install_base_packages else 'Skipped' }}
          CVMFS client: {{ 'Installed' if install_cvmfs else 'Skipped' }}
          RKE2 prerequisites: {{ 'Installed' if install_rke2_prerequisites else 'Skipped' }}
          Helm: {{ 'Installed with pre-configured repositories' if install_helm else 'Skipped' }}

    - name: Verify key components are accessible
      ansible.builtin.command: "{{ item }}"
      register: version_checks
      loop:
        - "helm version --short"
        - "cvmfs_config probe"
      failed_when: false
      changed_when: false

    - name: Display component versions
      ansible.builtin.debug:
        msg: "{{ item.cmd }} -> {{ item.stdout | default(item.stderr) }}"
      loop: "{{ version_checks.results }}"

    - name: Create image preparation completion marker
      ansible.builtin.copy:
        content: |
          Image prepared on: {{ ansible_date_time.iso8601 }}

          Installed components:
          - RKE2 prerequisites: {{ rke2_version }}
          - Helm: {{ helm_version }} with pre-configured repositories (stable, cloudve)
          - CVMFS client with repositories: {{ cvmfs_verify_repos | join(', ') if install_cvmfs else 'NONE' }}

          Next steps:
          1. Create image snapshot from this instance
          2. Use prepared image for faster RKE2 cluster deployment
        dest: /etc/galaxy-k8s-boot-image-info
        mode: "0644"

    - name: Final cleanup and preparation for imaging
      block:
        - name: Clear systemd journal (if needed for image size reduction)
          ansible.builtin.command: journalctl --vacuum-time=1s
          failed_when: false
          changed_when: false  # This doesn't change system state meaningfully

        - name: Clear network configuration that might be host-specific
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          loop:
            - /etc/netplan/50-cloud-init.yaml
            - /etc/network/interfaces.d/50-cloud-init.cfg
          failed_when: false
