---
- name: Setup NFS Provisioner
  hosts: controllers[0]
  gather_facts: false  # Use facts from main deploy.yml playbook
  vars:
    persistence_storage_class: blockstorage
    size: "10Gi"
    default: false
    allow_expansion: true
    reclaim: Delete
    version: 1.8.0
  environment:
    KUBECONFIG: "{{ '/root' if ansible_user == 'root' else '/home/' + ansible_user }}/.kube/config"
  tasks:
    - name: Stop conflicting host NFS services
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - rpc-statd.service
        - rpcbind.service
      ignore_errors: true
      become: true

    - name: Create the NFS namespace
      kubernetes.core.k8s:
        kind: Namespace
        name: nfs-provisioner
        state: present

    - name: Install the Ganesha NFS Helm repository
      kubernetes.core.helm_repository:
        name: nfs-ganesha
        repo_url: https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner/
        state: present

    - name: Helm install Ganesha NFS
      kubernetes.core.helm:
        name: nfs-provisioner
        namespace: nfs-provisioner
        chart_ref: nfs-ganesha/nfs-server-provisioner
        chart_version: "{{ version }}"
        values:
          service:
            type: LoadBalancer
            annotations:
              networking.gke.io/load-balancer-type: "Internal"
            loadBalancerSourceRanges:
              - "10.0.0.0/8"     # Internal GCP networks only
          persistence:
            enabled: true
            storageClass: "{{ persistence_storage_class }}"
            size: "{{ size }}"
          storageClass:
            create: true
            defaultClass: "{{ default }}"
            allowVolumeExpansion: "{{ allow_expansion }}"
            reclaimPolicy: "{{ reclaim }}"
            mountOptions:
              - nfsvers=4.2
              - retrans=2
              - timeo=30
              - lock        # Enable NFS locking
              - hard        # Ensure reliable locking
