- name: Basic setup of the node
  import_playbook: setup.yml

#- name: Setup RKE
#  hosts: rke_cluster
#  roles:
#    - role: rke
#      tags: ["controller", "agent", "rke"]
#      when: k8s_provider == "rke"

- name: Setup K3S
  import_playbook: k3s/site.yml
#  when: k8s_provider == "k3s"

- name: Install Helm
  import_playbook: helm.yml

- name: Install NFS
  import_playbook: nfs.yml

- name: Configure Ingress
  import_playbook: ingress.yml
#  when: kube_cloud_provider == "aws" or kube_cloud_provider == "openstack"

- name: Configure storage
  import_playbook: storage.yml
  vars:
    kube_cloud_provider: "{{ kube_cloud_provider }}"

#- name: Install Galaxy on AWS
#  import_playbook: galaxy.yml
#  vars:
#    values_file: values/aws.yml
#    admin_users: "suderman@jhu.edu"
#    api_key: "galaxypassword"
#  when: kube_cloud_provider == "aws"
#
#- name: Install Galaxy on GCP
#  import_playbook: galaxy.yml
#  vars:
#    values_file: values/gcp.yml
#    admin_users: "suderman@jhu.edu"
#    api_key: "galaxypassword"
#  when: kube_cloud_provider == "gcp"

- name: Install Galaxy on OpenStack
  import_playbook: galaxy.yml
  vars:
    values_file: values/openstack.yml
    admin_users: "suderman@jhu.edu"
    api_key: "galaxypassword"
#  when: kube_cloud_provider == "openstack"
