- name: Basic setup of the node
  import_playbook: setup.yml

- name: Setup Kubernetes
  import_playbook: k3s/site.yml

- name: Install Helm
  import_playbook: helm.yml

- name: Install NFS
  import_playbook: nfs-traditional.yml
  #import_playbook: nfs.yml

- name: Configure Ingress
  import_playbook: ingress.yml

- name: Configure storage
  import_playbook: storage.yml

- name: Install Galaxy
  import_playbook: galaxy_app.yml
  vars:
    values_file: "values/{{ chart_values_file | default('accp.yml') }}"
    gxy_admin_users: "{{ galaxy_admin_users | default('') }}"
    gxy_api_key: "{{ galaxy_api_key }}"
  when: application == "galaxy"

- name: Install Pulsar
  import_playbook: pulsar.yml
  vars:
    pulsar_api_key: "{{ pulsar_api_key }}"
  when: application == "pulsar"
