---
- name: Install Pulsar
  hosts: controllers[0]
  vars:
    chart: cloudve/pulsar
    version: 0.2.0
  environment:
    KUBECONFIG: "{{ '/root' if ansible_user == 'root' else '/home/' + ansible_user }}/.kube/config"
  tasks:
    - name: Create the Pulsar namespace
      kubernetes.core.k8s:
        kind: Namespace
        name: pulsar
        state: present

    - name: Helm install Pulsar
      kubernetes.core.helm:
        name: pulsar
        namespace: pulsar
        chart_ref: "{{ chart }}"
        chart_version: "{{ version }}"
        values:
          api_key: "{{ pulsar_api_key }}"
          refdata:
            enabled: false
