---
# RKE2 cluster setup playbook

- name: Deploy RKE2 Kubernetes cluster
  hosts: all
  become: true
  vars:
    # RKE2 configuration variables
    rke2_token: "{{ rke2_cluster_token | default('defaultSecret12345') }}"
    rke2_version: "{{ rke2_cluster_version | default('v1.33.4+rke2r1') }}"
    rke2_api_ip: "{{ hostvars[groups['masters'][0]]['ansible_default_ipv4']['address'] }}"
    rke2_download_kubeconf: true
    rke2_download_kubeconf_path: /tmp
    rke2_cluster_group_name: k8s_cluster
    rke2_servers_group_name: masters
    rke2_agents_group_name: workers
    # Configure for single-node or multi-node based on inventory
    rke2_ha_mode: "{{ groups['masters'] | length > 1 }}"
  roles:
    - role: lablabs.rke2

- name: Post-cluster configuration
  hosts: masters[0]
  tasks:
    - name: Wait for RKE2 to be ready
      wait_for:
        port: 6443
        host: "{{ ansible_default_ipv4.address }}"
        delay: 30
        timeout: 300

    - name: Create .kube directory for ansible user
      file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
      become: true

    - name: Copy kubeconfig to ansible user
      copy:
        src: /etc/rancher/rke2/rke2.yaml
        dest: "{{ ansible_env.HOME }}/.kube/config"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
        remote_src: true
      become: true

    - name: Update kubeconfig server address
      replace:
        path: "{{ ansible_env.HOME }}/.kube/config"
        regexp: 'https://127\.0\.0\.1:6443'
        replace: "https://{{ ansible_default_ipv4.address }}:6443"
