---
- name: Setup storage
  hosts: controllers[0]
  vars:
    cluster_hostname: galaxy
    cinder_csi_version: 2.31.2
    block_storage_disk_path: /mnt/block_storage
  environment:
    KUBECONFIG: "{{ '/root' if ansible_user == 'root' else '/home/' + ansible_user }}/.kube/config"
  tasks:
    # Use k3s built-in local-path provisioner instead of creating duplicate
    # Removed: templates/hostpath_storage_class.yaml.j2 (causes duplicate provisioner)
    
    - name: Render the elastic block storage class
      kubernetes.core.k8s:
        template:
          path: templates/block_storage_storageclass.yml.j2
        state: present
