# The latest development build
image:
  repository: ksuderman/galaxy-gpu
  tag: "26.2.dev0"

jobs:
  rules:
    tpv_rules_local.yml:
      destinations:
        gcp_batch:
          params:
            job_id_prefix: galaxy-gpu
      tools:
        toolshed.g2.bx.psu.edu/repos/goeckslab/image_learner/image_learner/.*:
          gpus: 1
          cores: 32
          mem: 116
